remote_theme: CaptainIRS/hacker-plus-theme

title: thng01's blogs
author: thng
description: This is where I save my Cybersecurity notes and CTF write-ups
disqus_forum_shortname:
google_site_verification_content: # The 'content' tag for site verification
google_analytics: # Your Google Analytics Tracking ID

# Usernames and badges
htb_badge_no: # 700619
thm_badge_no: # 962816
show_thm_htb_badges_in_nav: false
github_username: thng01
gitlab:
medium:
stackoverflow:
hacker_news:
linkedin:
twitch:
youtube:
twitter: 
facebook:
instagram:
reddit:
pinterest:
telegram:
steam:

# -------DO NOT ALTER -------#
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
exclude: [
   /*/*/_problems/*,
   scripts
]
plugins:
   - jekyll-seo-tag
   - jemoji
   - jekyll-sitemap
   - jekyll-github-metadata
collections:
   pages:
      output: true
      permalink: /:name
   writeups:
      output: true
   solutions:
      output: true
   blog:
      output: true
